import type { ColorPalette } from './types';

export const PRESET_PALETTES: ColorPalette[] = [
  {
    id: 'hospital-purple',
    name: 'Hospital Purple',
    description: 'Sistema médico - Default',
    colors: {
      primary: '#6b32e8',
      primaryLight: '#7c50f5',
      secondary: '#4a1aa8',
      background: '#f7f8fa',
      surface: '#ffffff',
      text: '#111827',
      textSecondary: '#6b7280',
      accent: '#3b82f6',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      border: '#e5e7eb',
    },
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep blue ocean',
    colors: {
      primary: '#0369a1',
      primaryLight: '#0ea5e9',
      secondary: '#023e8a',
      background: '#f0f9ff',
      surface: '#e0f2fe',
      text: '#0c4a6e',
      textSecondary: '#075985',
      accent: '#38bdf8',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      border: '#bae6fd',
    },
  },
  {
    id: 'forest-sanctuary',
    name: 'Forest Sanctuary',
    description: 'Green natural healing',
    colors: {
      primary: '#15803d',
      primaryLight: '#22c55e',
      secondary: '#166534',
      background: '#f0fdf4',
      surface: '#dcfce7',
      text: '#14532d',
      textSecondary: '#166534',
      accent: '#4ade80',
      success: '#16a34a',
      warning: '#ca8a04',
      error: '#dc2626',
      border: '#bbf7d0',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm orange comfort',
    colors: {
      primary: '#c2410c',
      primaryLight: '#ea580c',
      secondary: '#9a3412',
      background: '#fff7ed',
      surface: '#ffedd5',
      text: '#431407',
      textSecondary: '#9a3412',
      accent: '#fb923c',
      success: '#16a34a',
      warning: '#f59e0b',
      error: '#dc2626',
      border: '#fed7aa',
    },
  },
  {
    id: 'midnight-command',
    name: 'Midnight Command',
    description: 'Dark mode control center',
    colors: {
      primary: '#818cf8',
      primaryLight: '#a5b4fc',
      secondary: '#6366f1',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      accent: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      border: '#334155',
    },
  },
  {
    id: 'slate-elegance',
    name: 'Slate Elegance',
    description: 'Professional gray',
    colors: {
      primary: '#475569',
      primaryLight: '#64748B',
      secondary: '#334155',
      background: '#f8fafc',
      surface: '#f1f5f9',
      text: '#0f172a',
      textSecondary: '#475569',
      accent: '#0ea5e9',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      border: '#e2e8f0',
    },
  },
  {
    id: 'rose-diagnostic',
    name: 'Rose Diagnostic',
    description: 'Rose medical diagnostics',
    colors: {
      primary: '#be185d',
      primaryLight: '#ec4899',
      secondary: '#9d174d',
      background: '#fdf2f8',
      surface: '#fce7f3',
      text: '#831843',
      textSecondary: '#9d174d',
      accent: '#f472b6',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      border: '#f9a8d4',
    },
  },
  {
    id: 'teal-vital',
    name: 'Teal Vital',
    description: 'Teal vitality & vitals',
    colors: {
      primary: '#0d9488',
      primaryLight: '#14b8a6',
      secondary: '#0f766e',
      background: '#f0fdfa',
      surface: '#ccfbf1',
      text: '#134e4a',
      textSecondary: '#115e59',
      accent: '#2dd4bf',
      success: '#0d9488',
      warning: '#ca8a04',
      error: '#dc2626',
      border: '#99f6e4',
    },
  },
];

export const DEFAULT_PALETTE = PRESET_PALETTES[0];

export function getPaletteById(id: string): ColorPalette | undefined {
  return PRESET_PALETTES.find((p) => p.id === id);
}
